//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayTimeSlot
    {
        public byte ID { get; set; }
        public string TimeSlot { get; set; }
        public Nullable<byte> AffectedHourSlot1 { get; set; }
        public Nullable<byte> AffectedHourSlot2 { get; set; }
    }
}
