//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string LicenceNumber { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string DefensiveNo { get; set; }
        public Nullable<System.DateTime> DefensiveExpiry { get; set; }
        public string Email { get; set; }
        public bool Resigned { get; set; }
        public string IDNumber { get; set; }
        public Nullable<short> Vehicle { get; set; }
    }
}
