//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleInstructor
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public Nullable<short> BookingType { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<bool> NoShow { get; set; }
        public Nullable<byte> UserID { get; set; }
        public Nullable<byte> AffectedHourSlot { get; set; }
        public Nullable<byte> ScheduleCreatedBy { get; set; }
        public Nullable<byte> ScheduleReconsDoneBy { get; set; }
        public string ReconsComment { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    }
}
