//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleItem
    {
        public int ID { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> Starting { get; set; }
        public Nullable<System.DateTime> Ending { get; set; }
        public string Description { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<bool> Cancelled { get; set; }
    }
}
