//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public byte ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> UserType { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Activated { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
    }
}
