//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public short ID { get; set; }
        public string VehicleRegistration { get; set; }
        public Nullable<byte> Make { get; set; }
        public Nullable<byte> Model { get; set; }
        public string ChasisNumber { get; set; }
        public string EngineNumber { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<byte> Colour { get; set; }
        public Nullable<byte> Fuel { get; set; }
        public Nullable<decimal> Milage { get; set; }
        public Nullable<decimal> Servicing { get; set; }
        public Nullable<System.DateTime> InsuranceExipry { get; set; }
        public Nullable<decimal> TankCapacity { get; set; }
        public Nullable<byte> VehicleType { get; set; }
    }
}
