//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleFueling
    {
        public short ID { get; set; }
        public Nullable<decimal> FuelAmount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<byte> UserID { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> Milage { get; set; }
        public Nullable<byte> VehicleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
    }
}
